### PR TITLE
fix: (IAC-632) tfvars PREFIX not applied to host nodes for k8s/Viya

### PR DESCRIPTION
**Pull request by riragh**
# Changes:
Updated the code to include the `<prefix>-eks-<node_name>` to show up for the node names.

# Test
Verified the changes by creating cluster, instance names for the nodes were populated with prefix. See internal ticket for details.

### CODE REVIEW

**Comment by thpang** [comment]
Are these the only updates needed given the module update and prefix issues? Just checking.

**Review by thpang — APPROVED** [review]
LGTM as long as this change matches the previous node pool naming.

**Comment by riragh** [comment]
The changes made in this PR match the <prefix>-<node_name> format as before.

**Review by jarpat — APPROVED** [review]
👍

**Comment by riragh** [comment]
I made the changes a while ago, so had to do a rebase and found the default nodes didn't pick the prefix so made the similar changes. See internal ticket for testing details.

**Comment by jarpat** [comment]
👍

**Comment by thpang** [comment]
LGTM

**Pull request merged**
