### PR TITLE
add cluster iam role to output

### PR DESCRIPTION
**Pull request by enderm**
simplifies scripting of role updates
example for logging/monitoring:
aws iam attach-role-policy --policy-arn "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" --role-name "$(terraform output -raw cluster_iam_role_arn | cut -d/ -f2)"
aws iam attach-role-policy --policy-arn "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy" --role-name "$(terraform output -raw worker_iam_role_arn | cut -d/ -f2)"

### CODE REVIEW

**Comment by thpang** [comment]
Are there docs or an issue that go along with this one?

**Comment by enderm** [comment]
no. We do not at this point document our outputs.
This turned out to be helpful for scripting the logging/monitoring setup. 
Found while evaluating https://rndjira.sas.com/browse/IAC-353
If the logging/monitoring folks want to use that output field when documenting their steps  they are free to do that (it'll be necessary to update their doc as part of fixing https://rndjira.sas.com/browse/IAC-353 anyways, I believe)

**Comment by thpang** [comment]
So the viya4-deployment repo integrates with the logging and monitoring repo so this will have to be coded in as needed there. If this is related there, open an issue and link this item there for reference. Thx.

**Review by thpang — APPROVED** [review]
LGTM. @enderm to create an issue on viya4-deployment referencing this one to incorporate for logging monitoring repo as needed.

**Comment by enderm** [comment]
IMO no changes to viya4-deployment are needed since it uses the tfstate to pick up the value, not the outputs.

**Pull request merged**
